import {
  Activity,
  Apple,
  BadgeIndianRupee,
  BarChart3,
  BookMarked,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  Car,
  Carrot,
  Circle,
  Clapperboard,
  Code2,
  Cookie,
  Cpu,
  Dumbbell,
  Factory,
  Film,
  Flame,
  Flower2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  HardHat,
  Heart,
  HeartPulse,
  Home,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  Leaf,
  LogIn,
  Megaphone,
  Milk,
  Package,
  Palette,
  PartyPopper,
  Plane,
  School,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SprayCan,
  Stethoscope,
  Tractor,
  TrendingUp,
  Trophy,
  Truck,
  UserCheck,
  UtensilsCrossed,
  Wallet,
  Wand2,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

// Icons referenced by string name from data (cloudes-data.ts, footer links).
// Listed explicitly on purpose: `import * as Icons from 'lucide-react'` pulled
// all ~1,500 lucide icons into every page's bundle (this component sits in the
// navbar), which made every route slow to compile and load. When data starts
// using a new icon name, add it here.
const icons: Record<string, LucideIcon> = {
  Activity,
  Apple,
  BadgeIndianRupee,
  BarChart3,
  BookMarked,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  Car,
  Carrot,
  Circle,
  Clapperboard,
  Code2,
  Cookie,
  Cpu,
  Dumbbell,
  Factory,
  Film,
  Flame,
  Flower2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  HardHat,
  Heart,
  HeartPulse,
  Home,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  Leaf,
  LogIn,
  Megaphone,
  Milk,
  Package,
  Palette,
  PartyPopper,
  Plane,
  School,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SprayCan,
  Stethoscope,
  Tractor,
  TrendingUp,
  Trophy,
  Truck,
  UserCheck,
  UtensilsCrossed,
  Wallet,
  Wand2,
  Wrench,
};

// Renders a lucide-react icon by its string name (used for Cloude icons stored as data/strings).
export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = icons[name];
  if (!Cmp) {
    if (process.env.NODE_ENV !== 'production') {
      console.warn(`<Icon name="${name}"> is not registered in components/icon.tsx — rendering a circle.`);
    }
    return <Circle {...props} />;
  }
  return <Cmp {...props} />;
}
